### PR TITLE
fix(WorkItemFilters): Support multiple workItem filters

### LINKED ISSUE #1415: Work Item Filters Does not work with multiple filters
**Describe the bug**
When attempting to use workItemFilters for change logs, if you try to use multiple filters, it puts them all as one comma separated filter.

**To Reproduce**
Add multiple filters to your release definition.

**Expected behavior**
When the WorkItemUpdater is attempting to match the filters, the for of should loop the filters instead of just always finding one filter.

**Screenshots**
N/A

**Platform Details (please complete the following information):**
 - OS: Mac/Windows
 - Version [e.g. CLI Version  eg: 1.6.6]: Latest
 - Salesforce CLI(sfdx cli) Version: Latest
 - CI Platform: GitHub

**Additional context**
This line https://github.com/dxatscale/sfpowerscripts/blob/524c283992508adcb413e2f3303c39558400a31d/packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts#L82

**Currently is:**
workitemFilters.push(releaseDefinition.changelog?.workItemFilters);

**Could be changed to:**
workitemFilters.push(...releaseDefinition.changelog?.workItemFilters);

I don't have access to create a branch for a pull request but I think if you do this and update the WorkItemUpdater.test.ts to have two string values it should cover the code and a good test to see it not work before this change.

### PR DESCRIPTION
**Pull request by brandonmikeska**
spread out the filters before pushing

### Summary generated by Reviewpad on 24 Oct 23 02:11 UTC
This pull request fixes an issue with multiple workItem filters. The patch spreads out the filters before applying them.

#### Checklist
All items have to be completed before a PR is merged

- [x] Adhere to [Contribution Guidelines](https://docs.dxatscale.io/about-us/contributing-to-dx-scale)
- [x] Updates to Decision Records considered?
- [x] Updates to documentation at [DX@Scale Guide](https://github.com/dxatscale/dxatscale-guide) considered?
- [x] Tested changes?
- [x] Unit Tests new and existing passing locally?

### CODE REVIEW

File: packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export default class ReleaseImpl {
             for (const releaseDefinition of this.props.releaseDefinitions) {
                 releaseName = releaseName.concat(releaseDefinition.release, '-');
                 if (releaseDefinition.changelog) {
-                    workitemFilters.push(releaseDefinition.changelog?.workItemFilters);
+                    workitemFilters.push(...releaseDefinition.changelog?.workItemFilters);
```
Comment (azlam-abdulsalam) [inline packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts]:
```suggestion
                    workitemFilters.push(...releaseDefinition?.changelog?.workItemFilters);
```

File: packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts [hunk 2]
```diff
@@ -79,7 +79,7 @@ export default class ReleaseImpl {
             for (const releaseDefinition of this.props.releaseDefinitions) {
                 releaseName = releaseName.concat(releaseDefinition.release, '-');
                 if (releaseDefinition.changelog) {
-                    workitemFilters.push(releaseDefinition.changelog?.workItemFilters);
+                    workitemFilters.push(...releaseDefinition?.changelog?.workItemFilters);
```
Comment (azlam-abdulsalam) [inline packages/sfpowerscripts-cli/src/impl/release/ReleaseImpl.ts]:
```suggestion
       if(releaseDefinition?.changelog?.workItemFilters) {
                    workitemFilters.push(...releaseDefinition?.changelog?.workItemFilters);
         }
```
