### PR TITLE
fix(npm-scope): converts npm scope to lowercase during publish and fetch

### LINKED ISSUE #799: Unable to fetch a npm based artifact in ADO when Org Name has mixed caps
npm scope provided in prepare should be automatically be using lowercase, as publish (or perhaps npm publish) uses lowercase.

This will reduce the need for a user to browse through documentation to understand what went wrong and helps with 

https://github.com/dxatscale/dxatscale-issue-registry/issues/2

### Discussed in https://github.com/Accenture/sfpowerscripts/discussions/797

<div type='discussions-op-text'>

<sup>Originally posted by **SadhamGithub** December 25, 2021</sup>
I am executing the **prepare-dev-pool** pipeline in Azure DevOps pipeline and I am getting this error

`Failed to execute scripts for test-oxfr3xr2eh3o@example.com with alias SO3 due to File not found: .sfpowerscripts/sourceTrackingFiles/test-oxfr3xr2eh3o@example.com/maxRevision.json`

The previous pipeline **quick-build-deploy** was successfully and **core** artifact was created successfully.
image

image

image

</div>

### PR DESCRIPTION
**Pull request by azlam-abdulsalam**
fix #799: converts npm scope to lowercase during publish and fetch. This ensures issues when a package is published, scope is already converted to lowercase and the package is not found during release/prepare/fetch when the scope is provided in upper/mixedcase

### CODE REVIEW

**Review by aly76 — APPROVED** [review]

File: packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactFromNPM.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export class FetchAnArtifactFromNPM implements FetchAnArtifact {
 
       let cmd: string;
       if (this.scope)
-        cmd = `npm pack @${this.scope}/${packageName}_sfpowerscripts_artifact`;
+        cmd = `npm pack @${this.scope.toLocaleLowerCase()}/${packageName}_sfpowerscripts_artifact`;
```
Comment (aly76) [inline packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactFromNPM.ts]: wrong method

**Review by aly76 — CHANGES_REQUESTED** [review]

File: packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactFromNPM.ts (hunk 1 above)
Comment (azlam-abdulsalam) [inline packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactFromNPM.ts]:
```suggestion
        cmd = `npm pack @${this.scope.toLowerCase()}/${packageName}_sfpowerscripts_artifact`;
```

**Review by azlam-abdulsalam — COMMENTED** [review]
Changed

**Review by aly76 — APPROVED** [review]
