### PR TITLE
fix(pool): fix error handling

### LINKED ISSUE #1219: sfpowerscripts:orchestrator:prepare fail when one scratchorg is allocated
**Describe the bug**
got an error `TypeError: this.pool.scratchOrgs is not iterable` on prepare when only one scratchorg is allocated

**Screenshots**
```
Current Allocation of ScratchOrgs in the pool dev: 9
Remaining Active scratchOrgs in the org: 66
ScratchOrgs to be allocated: 1
Generate Scratch Orgs..
Waiting for all scratch org request to complete, Please wait
Requesting Scratch Org SO1..
Creation request for Scratch Org  SO1  is completed successfully in  00:04:24.411
Created 1 of 1 successfully with 0 failures in 00:04:26.031
ERROR running sfpowerscripts:orchestrator:prepare:  Unable to execute command .. TypeError: this.pool.scratchOrgs is not iterable
```

### PR DESCRIPTION
**Pull request by azlam-abdulsalam**
fix incorrect handling of errors during timeout etc
make it more robust by refactoring the pool create

#### Checklist
All items have to be completed before a PR is merged

- [x] Adhere to [Contribution Guidelines](https://docs.dxatscale.io/about-us/contributing-to-dx-scale)
- [x] Updates to Decision Records considered?
- [x] Updates to documentation at [DX@Scale Guide](https://github.com/dxatscale/dxatscale-guide) considered?
- [x] Tested changes?
- [x] Unit Tests new and existing passing locally?

### CODE REVIEW

File: packages/core/src/scratchorg/pool/PoolCreateImpl.ts [hunk 1]
```diff
@@ -66,42 +65,60 @@ export default class PoolCreateImpl extends PoolBaseImpl {
...
+                    this.pool,
+                    this.scratchOrgInfoFetcher,
+                    this.scratchOrgInfoAssigner
+                );
+            }
+        } catch (error) {
+            return err({
+                success: 0,
+                failed: this.pool.failedToCreate,
+                message: `All requested scratch orgs failed to provision, Please check your code or config \m Failed with ${error.message}`,
```
Comment (azlam-abdulsalam) [inline packages/core/src/scratchorg/pool/PoolCreateImpl.ts]:
```suggestion
                message: `All requested scratch orgs failed to provision, Please check your code or config \n Failed with ${error.message}`,
```

**Review by vuha-acn — APPROVED** [review]
Gtm
