### PR TITLE
fix(deploy): ensure max retry count is set to 10

### LINKED ISSUE #1262: maxretrycount flag not working for package deployment
**Description:**
When deploying packages, the maxretrycount flag (in the prepare command) does not appear to be functioning properly. Despite setting the maxRetryCount value to 4 in the configuration files, the command only retries twice before failing in some cases.

**Expected behavior:**
When a package deployment fails, the command should automatically retry the specified number of times as set by the maxRetryCount value. In this case, it should stop retrying after 4 attempts to install the package.

**Platform Details:**
 - window 10
 - sfpowerscipt version: 20.25.9
 - Salesforce CLI Version: 7.186.2

### PR DESCRIPTION
**Pull request by azlam-abdulsalam**
deploy doesnt respect max retry count, it is always set at 2 retries, as it was incorrectly set. The
fix sets a  max default of 10 with a break if earlier if the maxRetry is lower

fixes #1262

#### Checklist
All items have to be completed before a PR is merged

- [x] Adhere to [Contribution Guidelines](https://docs.dxatscale.io/about-us/contributing-to-dx-scale)
- [ ] Updates to Decision Records considered?
- [ ] Updates to documentation at [DX@Scale Guide](https://github.com/dxatscale/dxatscale-guide) considered?
- [ ] Tested changes?
- [ ] Unit Tests new and existing passing locally?

### CODE REVIEW

File: packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts [hunk 1]
```diff
@@ -241,7 +241,7 @@ export default class DeployImpl {
                             } else return false;
                         }
                     },
-                    { retries: 1, minTimeout: 2000 }
+                    { retries: 10, minTimeout: 2000 }
```
Comment (azlam-abdulsalam) [inline packages/sfpowerscripts-cli/src/impl/deploy/DeployImpl.ts]:
```suggestion
                    { retries: 10, minTimeout: 30000 }
```
